### ISSUE TITLE
Do we really need initialization of collection using external message?

### ISSUE THREAD

**Issue by xssnick** [TelegramMessenger/telemint#14]
What is the reason behind initialization of collection using external message?

Seems like someone can init your contract faster than you 😄 

I think we can just deploy contract with desired data already or use same approach as we have in [NFT contract](https://github.com/ton-blockchain/token-contract/blob/main/nft/nft-item.fc#L117)

**Comment by arseny30** [comment]
It is just for the convenience of initialization.

Anyway, if somebody somehow initialized it earlier (one should know all initialization data for this) – good for us.

**Comment by xssnick** [comment]
What if he will use unwanted data for initialization, for example diff owner_key?

**Comment by arseny30** [comment]
He can't. The address of a smart contract depends on its initial data and code. And initial data includes the owner key.

**Comment by xssnick** [comment]
But I don't see any check for an owner key in external message, it just saves what it got from first user

**Comment by arseny30** [comment]
If somebody sends a message with StateInit , StateInit is used to recalculate the address. If the calculated address doesn't match the destination address, then the message is discarded

https://github.com/ton-blockchain/ton/blob/master/crypto/block/transaction.cpp#L1015
3.1.9. from tblkch.pdf is also relevant.

**Comment by xssnick** [comment]
> If somebody sends a message with StateInit , StateInit is used to recalculate the address. If the calculated address doesn't match the destination address, then the message is discarded
> 
> https://github.com/ton-blockchain/ton/blob/master/crypto/block/transaction.cpp#L1015 3.1.9. from tblkch.pdf is also relevant.

1. You deploy contract with state init (which is untouched yet) 
2. I send external message to your contract and setting my own key
3. Your contract belongs to me and cannot be modified by you

**Comment by arseny30** [comment]
recv_external will only change the `touched` field of the data. The `public_key` will be kept the same as before.

Am I missing something? 
The only way to set `public_key` is to pass it in the StateInit part of the message. StateInit is fixed by account address.
recv_external and recv_internal do not change `public_key` at all.

**Comment by 11771100** [comment]
yes

**Comment by xssnick** [comment]
Ah, sorry, I see now, thought `unpack_collection_data` uses `in_msg`, but it unpacks storage. Then everything is fine.

**Comment by mhbdev** [comment]
If there is no use of `touched` value anywhere why do we need that external initialization? It seem weird having this extra bit in our storage with no use case.
