### ISSUE TITLE
A problem in nftltem ,,, By giving permission to its owner 

### ISSUE THREAD

**Issue by Ameralsamt** [TelegramMessenger/telemint#16]
I think there is a problem with giving permissions to the owner nftltem This is in order to open an automatic bid.... I believe that the bidding should be created under the supervision of one of the supervisors and then decide whether to accept or not...because it is important to work continuously to ensure the quality of service and growth remains dominant.

**Comment by 11771100** [comment]
أعتقد أن هناك مشكلة في إعطاء أذونات للمالك nftltem وهذا من أجل فتح مزايدة تلقائية .... أعتقد أن المزايدة يجب أن يتم إنشاؤها تحت إشراف أحد المشرفين ثم تقرر ما إذا كنت ستقبل أم لا ... لأنه من المهم العمل باستمرار لضمان جودة الخدمة ويظل النمو هو المسيطر. ويكون هذا الأمر مهم جدا لحل المشكله
ارجوا الاهتمام

**Comment by Ameralsamt** [comment]
Of course, this is a wonderful thing, and such a thing should be considered in order for everything to become better

**Comment by Ameralsamt** [comment]
Please reconsider it is important
