### ISSUE TITLE
Colour

### ISSUE THREAD

**Issue by MUSNIXmusnix** [TelegramMessenger/telemint#20]
-Colour effect
Bright colour needed,eg(green/white- orange)
-Servicer slow (massage,app delay massage when sent and receive)
-rebot slow when open

**Comment by josha12345** [comment]
yes

**Comment by Railok14** [comment]
@levlam

**Comment by nhymnehe** [comment]
![IMG_1666451712609_1666460916410](https://user-images.githubusercontent.com/116465244/197365949-9b5cdbf5-d0f4-418a-997d-ae03f92864a0.jpg)
