### ISSUE TITLE
What will be if the domain contains 0?

### ISSUE THREAD

**Issue by mytonwallet** [TelegramMessenger/telemint#28]
https://github.com/TelegramMessenger/telemint/blob/main/func/common.fc#L70
For example - codex0a\0test\0 -> codex will be resolved, but should be codex0a
Potentially it is possible to forge domain, for example to create ton0a\0test\0 -> ton, but originaly must be only ton\0test\0 -> ton

**Comment by arseny30** [comment]
I don't quite follow. The function splits the string by '\0' not by '0'.  ASCII code of '0' is 48.

**Comment by mytonwallet** [comment]
https://github.com/TelegramMessenger/telemint/blob/main/func/common.fc#L75
Ok, but here is
```
need_break = char == 0;
```
Sorry, but how does it work then to understand that it is was 48?
