### ISSUE TITLE
How to mint NFT from username?

### ISSUE THREAD

**Issue by ArtemBernatskyy** [TelegramMessenger/telemint#71]
Hello, I'm sorry but can't find any info about how to mint NFT from username that you control? Thx!

**Comment by AntonChekhov24** [comment]
??? Не понимаю

пт, 11 нояб. 2022 г., 03:10 Artem Bernatskyy ***@***.***>:

**Comment by ArtemBernatskyy** [comment]
Nevermind, Telegram just added an option to convert basic usernames into collectibles. Closing this issue.

**Comment by Qiadail** [comment]
qiad ail

في الجمعة، ١١ نوفمبر، ٢٠٢٢ ٣:١٠ ص Artem Bernatskyy ***@***.***>
كتب:
