### ISSUE TITLE
just_thot: tokens might collide

### ISSUE THREAD

**Issue by Whynotsavage** [TelegramMessenger/telemint#8]
would not the tokens declared in the messages such as TeleitemAuctionConfig , TelemintText , TeleitemAuctionConfig, NftRoyaltyParams , TelemintTokenInfo collide with each other such as [nft-item.fc], [nft-collection.fc] [common.fc] present in internal/external messages? 
or is it neglected as they're messages in the interface !

(if this is just irrelvant we'll just delete this issue)

**Comment by arseny30** [comment]
TeleitemAuctionConfig , TelemintText  and others are not internal messages. They are just stored inside internal messages.
And when we parse TeleitemAuctionConfig inside a message, we always know that we expect TeleitemAuctionConfig and not something else.

**Comment by Whynotsavage** [comment]
> TeleitemAuctionConfig , TelemintText and others are not internal messages. They are just stored inside internal messages. And when we parse TeleitemAuctionConfig inside a message, we always know that we expect TeleitemAuctionConfig and not something else.

Aight😅
